### ISSUE TITLE
Wheel does not contain code

### ISSUE THREAD

**Issue by jwodder** [righthandabacus/filesnitch#1]
The wheel (`.whl`) file for version 0.1 of this project on PyPI does not contain any code.  This is due to the fact that `filesnitch.py` is a flat module, rather than a package, and so `setuptools.find_packages()` does not find it.  The correct way to declare a flat-module project in `setup.py` is by replacing the `packages=...` argument to `setup()` with a `py_modules` argument, like so:

```
py_modules=['filesnitch']
```

**Comment by righthandabacus** [comment]
Oh thanks a lot for this. I fixed and updated that to 0.1.1
